site: Glanceyes (SeonHo Lee)

url: 
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /project/:slug
  archives:
    output: true
    permalink: /archive/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "archives"
    values:
      layout: "archive"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

exclude:
  - _backup
  - vendor
  - Gemfile
  - Gemfile.lock

future: true

timezone: Asia/Seoul
